package com.xt.mybatis.mapper2;

import com.xt.mybatis.bean2.Department2;
import com.xt.mybatis.bean2.Department2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Department2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    long countByExample(Department2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int deleteByExample(Department2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int insert(Department2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int insertSelective(Department2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    List<Department2> selectByExample(Department2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    Department2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Department2 record, @Param("example") Department2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByExample(@Param("record") Department2 record, @Param("example") Department2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByPrimaryKeySelective(Department2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByPrimaryKey(Department2 record);
}