package com.xt.mybatis.mapper2;

import com.xt.mybatis.bean2.Employee2;
import com.xt.mybatis.bean2.Employee2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Employee2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    long countByExample(Employee2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int deleteByExample(Employee2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int insert(Employee2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int insertSelective(Employee2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    List<Employee2> selectByExample(Employee2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    Employee2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employee2 record, @Param("example") Employee2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByExample(@Param("record") Employee2 record, @Param("example") Employee2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByPrimaryKeySelective(Employee2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 08 11:59:33 CST 2019
     */
    int updateByPrimaryKey(Employee2 record);
}